fastqs:
    "/datahome/oenothera/transcripts/assemblies/snakemake-trinity/fastqs"
results_loc:
        "/datahome/oenothera/transcripts/assemblies/snakemake-trinity/results"
test:
    "/datahome/oenothera/transcripts/assemblies/snakemake-trinity/test"
